### ISSUE TITLE
Running Predictions with GOLFv2 Models

### ISSUE THREAD

**Issue by joshemorris** [yoyololicon/golf#14]
Hey there @yoyololicon, 

Thanks for making your code publicly available! 

I'm trying to use the predict endpoint of autoencode.py.

I have successfully run prediction with GOLFv1 using the following command:
```
python autoencode.py predict -c ckpts/interspeech24/golf-v1/config.yaml --ckpt_path ckpts/interspeech24/golf-v1/checkpoints/epoch=537-step=993148-val_loss=3.086.ckpt --trainer.logger false --seed_everything false --data.wav_dir ./data/audio/ --trainer.callbacks+=ltng.cli.MyPredictionWriter --trainer.callbacks.output_dir ./data/ --model ltng.ae.VoiceAutoEncoder
```

When I try to run the newer GOLF models using a similar command, I'm getting the following error:
```
error: Parser key "model":
  Does not validate against any of the Union subtypes
  Subtypes: (<class 'lightning.pytorch.core.module.LightningModule'>, <class 'NoneType'>)
  Errors:
    - Problem with given class_path 'lightning.LightningModule':
        Validation failed: Key 'decoder.init_args.harm_oscillator.init_args.hop_rate' is not expected
    - Expected a <class 'NoneType'>
```

Am I making a mistake here? Is there a different model argument I should provide for the new GOLF models?

**Comment by joshemorris** [comment]
Following up

I was able to get `GOLF-ff` to run with the following command, based on the section on `GOLF-fs` later in the README:
```
python autoencode.py predict -c ckpts/interspeech24/golf-ff/config.yaml --ckpt_path ckpts/interspeech24/golf-ff/checkpoints/epoch=539-step=996840-val_loss=3.073.ckpt --trainer.logger false --seed_everything false --data.wav_dir ./data/audio/ --trainer.callbacks+=ltng.cli.MyPredictionWriter --trainer.callbacks.output_dir ./data/golf-ff/ --model.decoder.end_filter models.filters.LTVMinimumPhaseFilterPrecise
```

I'm not sure that is correct though. It also doesn't work for the `GOLF-ss` model.

**Comment by yoyolicoris** [comment]
Hi @joshemorris ,

I guess you probably forgot the `--model ltng.ae.VoiceAutoEncoder` argument.
The following command works for me:
```bash
python autoencode.py predict --model ltng.ae.VoiceAutoEncoder --config ckpts/interspeech24/golf-ss/config.yaml --ckpt_path ckpts/interspeech24/golf-ss/checkpoints/epoch\=539-step\=996840-val_loss\=3.064.ckpt --trainer.logger false --seed_everything false --data.wav_dir /mnt/Data/Datasets/VCTK-Corpus-0.92-raw/24k-mic1/ --trainer.callbacks+=ltng.cli.MyPredictionWriter --trainer.callbacks.output_dir ./data/ 
```

BTW, there were a few errors in the readme. I have fixed them.
You can check again to ensure everything is correct.
Let me know if you are still having issues running the code.

**Comment by joshemorris** [comment]
Hey @yoyololicon

Thanks for the quick response!

The command you suggested worked for me. 🎉 

It seems that the position of the `--model` arg is important. I was supplying it as the last arg and I don't think it was getting recognized correctly. Making it the first argument works. Thank you very much!

**Comment by yoyolicoris** [comment]
I'm glad that helps!
Yeah, the jsonargparser processes the arguments in order, so the position is important.

**Comment by yoyolicoris** [comment]
Hey @joshemorris,
I decided to just put `VoiceAutoEncoder` inside the checkpoint configs so `--model` can be omitted from the command.
I have pushed the changes. Please pull the latest version so this can take effect.

**Comment by joshemorris** [comment]
Just pulled and tested it out. It is working for me! Thank you!
